### ISSUE TITLE
Merge的小疑问

### ISSUE THREAD

**Issue by Jchaokai** [roseduan/minidb#9]
https://github.com/roseduan/minidb/blob/ab5768a129eb3d670d70d2a3ff0274c916cf53a3/db.go#L104

不应该更新dbFile这个对象吗，还用临时文件对象？

		newdbFile, _ := NewDBFile(db.dirPath)
		db.dbFile = newdbFile

**Comment by Jchaokai** [comment]
还有merge时，更新indexes是不是要考虑锁的问题

**Comment by roseduan** [comment]
1、临时文件就是最新的了

**Comment by roseduan** [comment]
2、是要加锁的，可以考虑用个原子更新

**Comment by Jchaokai** [comment]
> 



> 1、临时文件就是最新的了

https://github.com/roseduan/minidb/issues/8#issuecomment-980521056

我的意思rename之后 db.dbFile这个变量不应该更新吗，debug时发现还是临时文件的名字，属性等
